version: '3.1'
services:
  postgres-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mamad
      POSTGRES_PASSWORD: 1122
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata 
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:
      POSTGRES_USER: mamad
      POSTGRES_PASSWORD: 1122
      POSTGRES_DB: zabbixNew
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - postgres-server
    volumes:
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
  
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:
      POSTGRES_USER: mamad
      POSTGRES_PASSWORD: 1122
      POSTGRES_DB: zabbixNew
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Asia/Kolkata"  
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - "8090:80"
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=127.0.0.1
  adminer:
    image: adminer
    restart: always
    ports:
      - "7070:7070"
  grafana-xxl:
    image: monitoringartist/grafana-xxl:latest
    ports:
     - "3000:3000"